const data = {
	product: [
		{
			_id: '1',
			name: 'Armário 1',
			category: 'Armário',
			image: '/images/prod-armario1.jpg',
			price: 1200,
			brand: 'Woodland',
			rating: 0.5,
			numReviews: 10,
			description: 'Armario rustico de madeira de acácia',
		},
		{
			_id: '2',
			name: 'Armário 2',
			category: 'Armário',
			image: '/images/prod-armario2.jpg',
			price: 1200,
			brand: 'Woodland',
			rating: 1.5,
			numReviews: 10,
			description: 'Armario rustico de madeira de acácia',
		},
		{
			_id: '3',
			name: 'Armário 3',
			category: 'Armário',
			image: '/images/prod-armario3.jpg',
			price: 1200,
			brand: 'Woodland',
			rating: 2.5,
			numReviews: 10,
			description: 'Armario rustico de madeira de acácia',
		},
		{
			_id: '4',
			name: 'Cadeira',
			category: 'Cadeira',
			image: '/images/prod-cadeira.jpg',
			price: 1200,
			brand: 'Woodland',
			rating: 3.5,
			numReviews: 10,
			description: 'Cadeira rustica de madeira de acácia',
		},
		{
			_id: '5',
			name: 'Cadeira 1',
			category: 'Cadeira',
			image: '/images/prod-cadeira1.jpg',
			price: 1200,
			brand: 'Woodland',
			rating: 4.5,
			numReviews: 10,
			description: 'Cadeira rustica de madeira de acácia',
		},
		{
			_id: '6',
			name: 'Cadeira 2',
			category: 'Cadeira',
			image: '/images/prod-cadeira2.jpg',
			price: 1200,
			brand: 'Woodland',
			rating: 5,
			numReviews: 10,
			description: 'Cadeira rustica de madeira de acácia',
		},
	],
};

export default data;